subroutine fakeG(Natoms, eleName, coord)
integer :: Natoms
real(8) :: coord(3,Natoms), hessian(3*Natoms,3*Natoms), hessianMW(3*Natoms,3*Natoms)
real(8) :: eval(3*Natoms), evec(3*Natoms,3*Natoms), freq(3*Natoms)
character(4) :: eleName(Natoms)
real(8) :: eleMass(Natoms)
integer :: eleNum(Natoms)
integer :: i,j,k, n1,n2,n3, m1,m2,m3! numbering the freq

! get mass and numbering
call eleName2Mass(Natoms, eleName, eleMass)
call eleName2Num(Natoms, eleName, eleNum)
!# write(*,*) eleNum

! calculate eigenvectors `ev`
call hessianCalc(Natoms, reshape(coord, (/3*Natoms/)), hessian)
call convMWhessian(Natoms, eleMass, hessian, hessianMW)
call evCalc(3*Natoms, hessianMW, eval, evec)
call calcFreq(Natoms, eval, freq)

open(325, file='freq_visual.log', status='unknown', action='write') ! fake -> fak -> 325
write(325,'(A)') '! Generated by ExactTS'
write(325,'(A)') '! Author: Wenbin FAN @ SHU'
write(325,'(A)') ' '
write(325,'(A)') ' 0 basis functions'
write(325,'(A)') ' 0 alpha electrons'
write(325,'(A)') ' 0 beta electrons'
write(325,'(A)') 'GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad'
write(325,'(A)') 'GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad'
write(325,'(A)') ' '
write(325,'(A)') '                         Standard orientation:'
write(325,'(A)') ' ---------------------------------------------------------------------'
write(325,'(A)') ' Center     Atomic      Atomic             Coordinates (Angstroms)'
write(325,'(A)') ' Number     Number       Type             X           Y           Z'
write(325,'(A)') ' ---------------------------------------------------------------------'
do i = 1, Natoms
write(325,'(I7, I11, I12, A, 3F12.6)') i, eleNum(i), 0, '    ', coord(1,i), coord(2,i), coord(3,i)
end do
write(325,'(A)') ' ---------------------------------------------------------------------'
write(325,'(A)') ' '
write(325,'(A)') ' SCF Done:        0.0000'
write(325,'(A)') ' '
write(325,'(A)') ' Harmonic frequencies (cm**-1), IR intensities (KM/Mole), Raman scattering'
write(325,'(A)') ' activities (A**4/AMU), depolarization ratios for plane and unpolarized'
write(325,'(A)') ' incident light, reduced masses (AMU), force constants (mDyne/A),'
write(325,'(A)') ' and normal coordinates:'
do i = 1, Natoms
n1 = (i-1)*3+1
n2 = (i-1)*3+2
n3 = (i-1)*3+3
write(325,'(3I23)') n1, n2, n3
write(325,'(3A23)') 'A', 'A', 'A'
write(325,'(A,F12.4,2F23.4)') ' Frequencies --', freq(n1), freq(n2), freq(n3)
write(325,'(A,F12.4,2F23.4)') ' IR Inten    --', 0.0, 0.0, 0.0
write(325,'(A)') '  Atom  AN      X      Y      Z        X      Y      Z        X      Y      Z  '
do j = 1, Natoms
m1 = (j-1)*3+1
m2 = (j-1)*3+2
m3 = (j-1)*3+3
write(325,'(I6,I4,3(A,3F7.3))') j, eleNum(j), &
'   ', evec(m1,n1), evec(m2,n1), evec(m3,n1), &
 '  ', evec(m1,n2), evec(m2,n2), evec(m3,n2), &
 '  ', evec(m1,n3), evec(m2,n3), evec(m3,n3)
end do

end do

write(325,'(A)') ' '
write(325,'(A)') ' Temperature     0.000 Kelvin.  Pressure   0.00000 Atm.'
do j = 1, Natoms
write(325,'(A,I6,A,I3,A,F10.5)') ' Atom', j, ' has atomic number', eleNum(j), ' and mass', eleMass(j)
end do
write(325,'(A)') ' Zero-point correction=                           0.000000 Hartree'
write(325,'(A)') ' Thermal correction to Energy=                    0.000000'
write(325,'(A)') ' Thermal correction to Enthalpy=                  0.000000'
write(325,'(A)') ' Thermal correction to Gibbs Free Energy=         0.000000'
write(325,'(A)') ' Electronic energy=                                      0.000000'
write(325,'(A)') ' Sum of electronic and zero-point Energies=              0.000000'
write(325,'(A)') ' Sum of electronic and thermal Energies=                 0.000000'
write(325,'(A)') ' Sum of electronic and thermal Enthalpies=               0.000000'
write(325,'(A)') ' Sum of electronic and thermal Free Energies=            0.000000'
write(325,'(A)') ' '
write(325,'(A)') ' Normal termination of Gaussian'



end subroutine

! calculate eigenvectors
! 2020-07-19 23:51:03 Wenbin, FAN @ SHU
subroutine evCalc(N, hessian, evReal, ev)
use lapack95, only: geev
integer, intent(in) :: N
real(8), intent(in) :: hessian(N,N)
real(8) :: evReal(N), evImag(N)
real(8) :: evl(N,N), evr(N,N)
real(8) :: work(N*N)
real(8), intent(out) :: ev(N,N)
integer :: info, i


call dgeev('V','V',N,hessian,N,evReal,evImag,evl,N,evr,N,work,N*N,info)
ev(1:N,1:N) = evl(1:N,1:N)

!# write(*,'(9F9.3)') evl
!# write(*,*) ''
!# write(*,'(9F9.3)') evr
!# write(*,*) ''
!# write(*,'(9F9.3)') evReal*1d3

end subroutine

! Get each mass from element name
subroutine eleName2Num(Natoms, eleName, eleNum)
implicit none
integer Natoms
character(4) :: allName(20) = &
(/'H', 'He',   'Li',   'Be',   'B', &
 'C',  'N',    'O',    'F',    'Ne', &
 'Na', 'Mg',   'Al',   'Si',   'P', &
 'S',  'Cl',   'Ar',   'K',    'Ca'/)
integer :: allNum(20) = &
(/1, 2, 3, 4, 5, &
 6, 7, 8, 9, 10, &
 11, 12, 13, 14, 15, &
 16, 17, 18, 19, 20/)
character(4) eleName(Natoms)
integer, intent(out) :: eleNum(Natoms)
integer i, j

do i = 1, Natoms
do j = 1, 20
!# write(*,*) i, j, eleName(i), allName(j)
if (trim(eleName(i)) == trim(allName(j))) then
eleNum(i) = allNum(j)
exit
!else
!write(*, *) '[ERROR] Element not supported: ', eleName(i)
end if
end do
end do
!# write(*,*) 'Element mass: '
!# write(*,*) eleMass
end subroutine
